#ifndef _GLOBAL_VAR_
#define _GLOBAL_VAR_

#define KEY 123
#define NAME_LEN 100
#define MOB_NO_LEN 11
#define MAX_BATCH_SIZE 100
#define MAX_ARR_SIZE 100
#define USER_NAME_LEN 10
#define USER_PASS_LEN 10
#define NO_OF_SKILLS 10
#define SKILLS_LEN 20
#define MAX_CLIENT_CONNECTION 10
#define CONNECTION_TIME_OUT_SECONDS 5
#define WATCHDOG_SLEEP_SECONDS 2

#define SERVER_CONNECTED "OK"
#define SERVER_NOT_CONNECTED "NOK"
#define SERVER_UNKNOWN_ERROR "FAILED"

enum enumMsgType{CLIENT_START=1};
enum enumStructID{EMP_INFO,CLIENT_INFO,QUERY_RESULT,QUERY_STRING,SERVER_ACK,WATCH_DOG};
enum enumServerAck{OK,ERROR};

#define _EMPDB_PATH_ "../database/empDB"


#endif //_GLOBAL_VAR_